export const DEMO_DATA_LABEL = "[DEMO DATA]";
export const REVIEWER_CASE_TITLE_PREFIX = "[REVIEW DEMO]";

export function demoId(index: number) {
  return `d3000000-0000-4000-8000-${index.toString().padStart(12, "0")}`;
}

export const DEMO_ACCOUNTS = [
  ...Array.from({ length: 2 }, (_, index) => ({
    email: `citizen.${index + 1}@demo-data.cpgrams.in`,
    fullName: `Demo Citizen ${String.fromCharCode(65 + index)}`,
    role: "citizen" as const,
    organizationCode: null,
    locationTerms: [] as string[],
  })),
  {
    email: "gro.urban.pune.a@demo-data.cpgrams.in",
    fullName: "Demo Urban GRO Pune A",
    role: "gro" as const,
    organizationCode: "DEMO-URBAN",
    locationTerms: ["Pune"],
  },
  {
    email: "gro.urban.pune.b@demo-data.cpgrams.in",
    fullName: "Demo Urban GRO Pune B",
    role: "gro" as const,
    organizationCode: "DEMO-URBAN",
    locationTerms: ["Pune"],
  },
  {
    email: "gro.urban.bengaluru@demo-data.cpgrams.in",
    fullName: "Demo Urban GRO Bengaluru",
    role: "gro" as const,
    organizationCode: "DEMO-URBAN",
    locationTerms: ["Bengaluru"],
  },
  {
    email: "gro.water.a@demo-data.cpgrams.in",
    fullName: "Demo Water GRO A",
    role: "gro" as const,
    organizationCode: "DEMO-WATER",
    locationTerms: [] as string[],
  },
  {
    email: "gro.water.b@demo-data.cpgrams.in",
    fullName: "Demo Water GRO B",
    role: "gro" as const,
    organizationCode: "DEMO-WATER",
    locationTerms: [] as string[],
  },
  {
    email: "gro.pension.a@demo-data.cpgrams.in",
    fullName: "Demo Pension GRO A",
    role: "gro" as const,
    organizationCode: "DEMO-PENSION",
    locationTerms: [] as string[],
  },
  {
    email: "gro.pension.b@demo-data.cpgrams.in",
    fullName: "Demo Pension GRO B",
    role: "gro" as const,
    organizationCode: "DEMO-PENSION",
    locationTerms: [] as string[],
  },
  {
    email: "nodal@demo-data.cpgrams.in",
    fullName: "Demo Nodal Supervisor",
    role: "nodal" as const,
    organizationCode: "DEMO-ROOT",
    locationTerms: [] as string[],
  },
  {
    email: "appellate@demo-data.cpgrams.in",
    fullName: "Demo Appellate Authority",
    role: "appellate" as const,
    organizationCode: "DEMO-APPEAL",
    locationTerms: [] as string[],
  },
] as const;

export const LEGACY_DEMO_AUTH_EMAILS = [
  "citizen.3@demo-data.cpgrams.in",
  "citizen.4@demo-data.cpgrams.in",
  "citizen.5@demo-data.cpgrams.in",
  "citizen@demo.cpgrams.in",
  "gro@demo.cpgrams.in",
  "nodal@demo.cpgrams.in",
  "appellate@demo.cpgrams.in",
  "gro.triage.pune.a@demo.cpgrams.in",
  "gro.triage.pune.b@demo.cpgrams.in",
  "gro.triage.bengaluru@demo.cpgrams.in",
] as const;

function legacyFixtureId(prefix: "90000000" | "91000000", index: number) {
  return `${prefix}-0000-4000-8000-${index.toString().padStart(12, "0")}`;
}

export const LEGACY_DEMO_CASE_IDS = [
  ...Array.from({ length: 11 }, (_, index) => legacyFixtureId("90000000", index + 1)),
  ...Array.from({ length: 14 }, (_, index) => legacyFixtureId("91000000", index + 1)),
] as const;

export const LEGACY_DEMO_CLUSTER_IDS = [legacyFixtureId("90000000", 500)] as const;

export const DEMO_ORGANIZATIONS = [
  {
    id: demoId(1),
    code: "DEMO-ROOT",
    name: "[DEMO] Civic Services Supervisory Group",
    level: "central_ministry",
    parentCode: null,
    stateName: null,
    isAppellate: false,
  },
  {
    id: demoId(2),
    code: "DEMO-URBAN",
    name: "[DEMO] Urban Lighting Office",
    level: "central_department",
    parentCode: "DEMO-ROOT",
    stateName: null,
    isAppellate: false,
  },
  {
    id: demoId(3),
    code: "DEMO-WATER",
    name: "[DEMO] Water Service Office",
    level: "central_department",
    parentCode: "DEMO-ROOT",
    stateName: null,
    isAppellate: false,
  },
  {
    id: demoId(4),
    code: "DEMO-PENSION",
    name: "[DEMO] Pension Service Office",
    level: "central_department",
    parentCode: "DEMO-ROOT",
    stateName: null,
    isAppellate: false,
  },
  {
    id: demoId(5),
    code: "DEMO-APPEAL",
    name: "[DEMO] Appellate Review Cell",
    level: "appellate_cell",
    parentCode: "DEMO-ROOT",
    stateName: null,
    isAppellate: true,
  },
] as const;

export const DEMO_CATEGORIES = [
  {
    id: demoId(101),
    code: "DEMO-URBAN-SERVICES",
    name: "[DEMO] Urban services",
    parentCode: null,
    organizationCode: "DEMO-URBAN",
    slaDays: 21,
    hint: "Prototype neighbourhood services",
  },
  {
    id: demoId(102),
    code: "DEMO-STREETLIGHT",
    name: "[DEMO] Streetlight problems",
    parentCode: "DEMO-URBAN-SERVICES",
    organizationCode: "DEMO-URBAN",
    slaDays: 15,
    hint: "Prototype streetlight outage or repair",
  },
  {
    id: demoId(103),
    code: "DEMO-WATER-SERVICES",
    name: "[DEMO] Water services",
    parentCode: null,
    organizationCode: "DEMO-WATER",
    slaDays: 21,
    hint: "Prototype water supply service",
  },
  {
    id: demoId(104),
    code: "DEMO-WATER-SUPPLY",
    name: "[DEMO] Water supply interruption",
    parentCode: "DEMO-WATER-SERVICES",
    organizationCode: "DEMO-WATER",
    slaDays: 14,
    hint: "Prototype interrupted or low-pressure supply",
  },
  {
    id: demoId(105),
    code: "DEMO-PENSION-SERVICES",
    name: "[DEMO] Pension services",
    parentCode: null,
    organizationCode: "DEMO-PENSION",
    slaDays: 30,
    hint: "Prototype pension payment service",
  },
  {
    id: demoId(106),
    code: "DEMO-PENSION-DELAY",
    name: "[DEMO] Pension payment delay",
    parentCode: "DEMO-PENSION-SERVICES",
    organizationCode: "DEMO-PENSION",
    slaDays: 21,
    hint: "Prototype delayed pension payment",
  },
] as const;

export type DemoCaseTag =
  | "fresh"
  | "unopened"
  | "sla-risk"
  | "critical"
  | "waiting-citizen"
  | "clarification-open"
  | "clarification-complete"
  | "documents-partial"
  | "documents-complete"
  | "interim"
  | "resolution-review"
  | "confirmed-resolved"
  | "partly-resolved"
  | "not-resolved"
  | "appealed"
  | "appeal-decided"
  | "transferred"
  | "transfer-risk"
  | "reminder"
  | "reminder-cap"
  | "manual-routing"
  | "closure-ready"
  | "streetlight-cluster"
  | "water-cluster"
  | "pension-cluster";

export interface DemoCaseDefinition {
  id: string;
  reference: string;
  title: string;
  citizen: number;
  organizationCode: "DEMO-URBAN" | "DEMO-WATER" | "DEMO-PENSION";
  categoryCode: "DEMO-STREETLIGHT" | "DEMO-WATER-SUPPLY" | "DEMO-PENSION-DELAY";
  location: string;
  state: string;
  district: string;
  submittedHoursAgo: number;
  slaWindowHours: number;
  administrativeState: string;
  outcomeState: string;
  confirmationState: string;
  openedHoursAgo?: number;
  lastActionHoursAgo?: number;
  reminderCount?: number;
  tags: DemoCaseTag[];
}

const urbanLocations = [
  ["Ward 12, Kothrud, Pune", "Maharashtra", "Pune"],
  ["Ward 14, Aundh, Pune", "Maharashtra", "Pune"],
  ["East Zone, Bengaluru", "Karnataka", "Bengaluru Urban"],
] as const;
const waterLocations = [
  ["Ward 7, Nashik", "Maharashtra", "Nashik"],
  ["Ward 9, Nashik", "Maharashtra", "Nashik"],
] as const;
const pensionLocations = [
  ["New Delhi", "Delhi", "New Delhi"],
  ["Pune", "Maharashtra", "Pune"],
] as const;

const rawCases: Array<Omit<DemoCaseDefinition, "id" | "reference">> = [
  {
    title: "Manual routing review for a streetlight and road-safety concern",
    citizen: 0,
    organizationCode: "DEMO-URBAN",
    categoryCode: "DEMO-STREETLIGHT",
    location: urbanLocations[0][0],
    state: urbanLocations[0][1],
    district: urbanLocations[0][2],
    submittedHoursAgo: 2,
    slaWindowHours: 360,
    administrativeState: "ASSIGNED",
    outcomeState: "UNRESOLVED",
    confirmationState: "NOT_REQUESTED",
    openedHoursAgo: 1,
    lastActionHoursAgo: 1,
    tags: ["fresh", "manual-routing", "streetlight-cluster"],
  },
  {
    title: "Fresh low-pressure water complaint",
    citizen: 1,
    organizationCode: "DEMO-WATER",
    categoryCode: "DEMO-WATER-SUPPLY",
    location: waterLocations[0][0],
    state: waterLocations[0][1],
    district: waterLocations[0][2],
    submittedHoursAgo: 3,
    slaWindowHours: 336,
    administrativeState: "ASSIGNED",
    outcomeState: "UNRESOLVED",
    confirmationState: "NOT_REQUESTED",
    openedHoursAgo: 2,
    lastActionHoursAgo: 2,
    tags: ["fresh", "water-cluster"],
  },
  {
    title: "Fresh pension credit delay",
    citizen: 2,
    organizationCode: "DEMO-PENSION",
    categoryCode: "DEMO-PENSION-DELAY",
    location: pensionLocations[0][0],
    state: pensionLocations[0][1],
    district: pensionLocations[0][2],
    submittedHoursAgo: 4,
    slaWindowHours: 504,
    administrativeState: "ASSIGNED",
    outcomeState: "UNRESOLVED",
    confirmationState: "NOT_REQUESTED",
    openedHoursAgo: 3,
    lastActionHoursAgo: 3,
    tags: ["fresh", "pension-cluster"],
  },
  {
    title: "Assigned streetlight case not opened for 25 hours",
    citizen: 3,
    organizationCode: "DEMO-URBAN",
    categoryCode: "DEMO-STREETLIGHT",
    location: urbanLocations[1][0],
    state: urbanLocations[1][1],
    district: urbanLocations[1][2],
    submittedHoursAgo: 48,
    slaWindowHours: 360,
    administrativeState: "ASSIGNED",
    outcomeState: "UNRESOLVED",
    confirmationState: "NOT_REQUESTED",
    tags: ["unopened", "streetlight-cluster"],
  },
  {
    title: "Assigned water case not opened for 49 hours",
    citizen: 4,
    organizationCode: "DEMO-WATER",
    categoryCode: "DEMO-WATER-SUPPLY",
    location: waterLocations[1][0],
    state: waterLocations[1][1],
    district: waterLocations[1][2],
    submittedHoursAgo: 72,
    slaWindowHours: 336,
    administrativeState: "ASSIGNED",
    outcomeState: "UNRESOLVED",
    confirmationState: "NOT_REQUESTED",
    tags: ["unopened", "water-cluster"],
  },
  {
    title: "Pension case at 76 percent of target",
    citizen: 0,
    organizationCode: "DEMO-PENSION",
    categoryCode: "DEMO-PENSION-DELAY",
    location: pensionLocations[1][0],
    state: pensionLocations[1][1],
    district: pensionLocations[1][2],
    submittedHoursAgo: 383,
    slaWindowHours: 504,
    administrativeState: "UNDER_EXAMINATION",
    outcomeState: "UNRESOLVED",
    confirmationState: "NOT_REQUESTED",
    openedHoursAgo: 360,
    lastActionHoursAgo: 20,
    tags: ["sla-risk", "pension-cluster"],
  },
  {
    title: "Streetlight case at 91 percent of target",
    citizen: 1,
    organizationCode: "DEMO-URBAN",
    categoryCode: "DEMO-STREETLIGHT",
    location: urbanLocations[2][0],
    state: urbanLocations[2][1],
    district: urbanLocations[2][2],
    submittedHoursAgo: 328,
    slaWindowHours: 360,
    administrativeState: "UNDER_EXAMINATION",
    outcomeState: "UNRESOLVED",
    confirmationState: "NOT_REQUESTED",
    openedHoursAgo: 300,
    lastActionHoursAgo: 24,
    tags: ["sla-risk", "streetlight-cluster"],
  },
  {
    title: "Critical breached streetlight repair",
    citizen: 2,
    organizationCode: "DEMO-URBAN",
    categoryCode: "DEMO-STREETLIGHT",
    location: urbanLocations[0][0],
    state: urbanLocations[0][1],
    district: urbanLocations[0][2],
    submittedHoursAgo: 390,
    slaWindowHours: 360,
    administrativeState: "UNDER_EXAMINATION",
    outcomeState: "UNRESOLVED",
    confirmationState: "NOT_REQUESTED",
    openedHoursAgo: 360,
    lastActionHoursAgo: 192,
    tags: ["critical", "streetlight-cluster"],
  },
  {
    title: "Critical breached water restoration",
    citizen: 3,
    organizationCode: "DEMO-WATER",
    categoryCode: "DEMO-WATER-SUPPLY",
    location: waterLocations[0][0],
    state: waterLocations[0][1],
    district: waterLocations[0][2],
    submittedHoursAgo: 370,
    slaWindowHours: 336,
    administrativeState: "UNDER_EXAMINATION",
    outcomeState: "UNRESOLVED",
    confirmationState: "NOT_REQUESTED",
    openedHoursAgo: 340,
    lastActionHoursAgo: 180,
    tags: ["critical", "water-cluster"],
  },
  {
    title: "Pension documents partly supplied",
    citizen: 4,
    organizationCode: "DEMO-PENSION",
    categoryCode: "DEMO-PENSION-DELAY",
    location: pensionLocations[0][0],
    state: pensionLocations[0][1],
    district: pensionLocations[0][2],
    submittedHoursAgo: 168,
    slaWindowHours: 504,
    administrativeState: "CLARIFICATION_REQUIRED",
    outcomeState: "UNRESOLVED",
    confirmationState: "NOT_REQUESTED",
    openedHoursAgo: 150,
    lastActionHoursAgo: 96,
    tags: ["waiting-citizen", "documents-partial", "pension-cluster"],
  },
  {
    title: "Water documents completed and review resumed",
    citizen: 0,
    organizationCode: "DEMO-WATER",
    categoryCode: "DEMO-WATER-SUPPLY",
    location: waterLocations[1][0],
    state: waterLocations[1][1],
    district: waterLocations[1][2],
    submittedHoursAgo: 144,
    slaWindowHours: 336,
    administrativeState: "CITIZEN_RESPONSE_RECEIVED",
    outcomeState: "UNRESOLVED",
    confirmationState: "NOT_REQUESTED",
    openedHoursAgo: 130,
    lastActionHoursAgo: 12,
    tags: ["documents-complete", "water-cluster"],
  },
  {
    title: "Clarification needed about water timings",
    citizen: 1,
    organizationCode: "DEMO-WATER",
    categoryCode: "DEMO-WATER-SUPPLY",
    location: waterLocations[0][0],
    state: waterLocations[0][1],
    district: waterLocations[0][2],
    submittedHoursAgo: 120,
    slaWindowHours: 336,
    administrativeState: "CLARIFICATION_REQUIRED",
    outcomeState: "UNRESOLVED",
    confirmationState: "NOT_REQUESTED",
    openedHoursAgo: 100,
    lastActionHoursAgo: 48,
    tags: ["waiting-citizen", "clarification-open", "water-cluster"],
  },
  {
    title: "Citizen answered streetlight location clarification",
    citizen: 2,
    organizationCode: "DEMO-URBAN",
    categoryCode: "DEMO-STREETLIGHT",
    location: urbanLocations[1][0],
    state: urbanLocations[1][1],
    district: urbanLocations[1][2],
    submittedHoursAgo: 96,
    slaWindowHours: 360,
    administrativeState: "CITIZEN_RESPONSE_RECEIVED",
    outcomeState: "UNRESOLVED",
    confirmationState: "NOT_REQUESTED",
    openedHoursAgo: 90,
    lastActionHoursAgo: 8,
    tags: ["clarification-complete", "streetlight-cluster"],
  },
  {
    title: "Streetlight inspection interim update recorded",
    citizen: 3,
    organizationCode: "DEMO-URBAN",
    categoryCode: "DEMO-STREETLIGHT",
    location: urbanLocations[0][0],
    state: urbanLocations[0][1],
    district: urbanLocations[0][2],
    submittedHoursAgo: 192,
    slaWindowHours: 360,
    administrativeState: "INTERIM_RESPONSE",
    outcomeState: "UNRESOLVED",
    confirmationState: "NOT_REQUESTED",
    openedHoursAgo: 180,
    lastActionHoursAgo: 6,
    tags: ["interim", "streetlight-cluster"],
  },
  {
    title: "Pension verification interim update recorded",
    citizen: 4,
    organizationCode: "DEMO-PENSION",
    categoryCode: "DEMO-PENSION-DELAY",
    location: pensionLocations[1][0],
    state: pensionLocations[1][1],
    district: pensionLocations[1][2],
    submittedHoursAgo: 240,
    slaWindowHours: 504,
    administrativeState: "INTERIM_RESPONSE",
    outcomeState: "UNRESOLVED",
    confirmationState: "NOT_REQUESTED",
    openedHoursAgo: 220,
    lastActionHoursAgo: 12,
    tags: ["interim", "pension-cluster"],
  },
  {
    title: "Streetlight repair awaiting citizen review",
    citizen: 0,
    organizationCode: "DEMO-URBAN",
    categoryCode: "DEMO-STREETLIGHT",
    location: urbanLocations[1][0],
    state: urbanLocations[1][1],
    district: urbanLocations[1][2],
    submittedHoursAgo: 240,
    slaWindowHours: 360,
    administrativeState: "RESOLUTION_PROVIDED",
    outcomeState: "RESOLUTION_PROPOSED",
    confirmationState: "AWAITING_CONFIRMATION",
    openedHoursAgo: 220,
    lastActionHoursAgo: 4,
    tags: ["resolution-review", "streetlight-cluster"],
  },
  {
    title: "Pension payment response awaiting review",
    citizen: 1,
    organizationCode: "DEMO-PENSION",
    categoryCode: "DEMO-PENSION-DELAY",
    location: pensionLocations[0][0],
    state: pensionLocations[0][1],
    district: pensionLocations[0][2],
    submittedHoursAgo: 300,
    slaWindowHours: 504,
    administrativeState: "RESOLUTION_PROVIDED",
    outcomeState: "RESOLUTION_PROPOSED",
    confirmationState: "AWAITING_CONFIRMATION",
    openedHoursAgo: 280,
    lastActionHoursAgo: 5,
    tags: ["resolution-review", "pension-cluster"],
  },
  {
    title: "Citizen confirmed streetlight restored",
    citizen: 2,
    organizationCode: "DEMO-URBAN",
    categoryCode: "DEMO-STREETLIGHT",
    location: urbanLocations[0][0],
    state: urbanLocations[0][1],
    district: urbanLocations[0][2],
    submittedHoursAgo: 480,
    slaWindowHours: 360,
    administrativeState: "RESOLUTION_PROVIDED",
    outcomeState: "RESOLVED",
    confirmationState: "CONFIRMED_RESOLVED",
    openedHoursAgo: 460,
    lastActionHoursAgo: 160,
    tags: ["confirmed-resolved", "closure-ready", "streetlight-cluster"],
  },
  {
    title: "Citizen confirmed water supply restored",
    citizen: 3,
    organizationCode: "DEMO-WATER",
    categoryCode: "DEMO-WATER-SUPPLY",
    location: waterLocations[1][0],
    state: waterLocations[1][1],
    district: waterLocations[1][2],
    submittedHoursAgo: 400,
    slaWindowHours: 336,
    administrativeState: "CLOSED",
    outcomeState: "RESOLVED",
    confirmationState: "CONFIRMED_RESOLVED",
    openedHoursAgo: 380,
    lastActionHoursAgo: 120,
    tags: ["confirmed-resolved", "water-cluster"],
  },
  {
    title: "Citizen confirmed pension arrears credited",
    citizen: 4,
    organizationCode: "DEMO-PENSION",
    categoryCode: "DEMO-PENSION-DELAY",
    location: pensionLocations[0][0],
    state: pensionLocations[0][1],
    district: pensionLocations[0][2],
    submittedHoursAgo: 600,
    slaWindowHours: 504,
    administrativeState: "CLOSED",
    outcomeState: "RESOLVED",
    confirmationState: "CONFIRMED_RESOLVED",
    openedHoursAgo: 580,
    lastActionHoursAgo: 200,
    tags: ["confirmed-resolved", "pension-cluster"],
  },
  {
    title: "Streetlight partly repaired; adjoining pole remains dark",
    citizen: 0,
    organizationCode: "DEMO-URBAN",
    categoryCode: "DEMO-STREETLIGHT",
    location: urbanLocations[1][0],
    state: urbanLocations[1][1],
    district: urbanLocations[1][2],
    submittedHoursAgo: 360,
    slaWindowHours: 360,
    administrativeState: "APPEAL_FILED",
    outcomeState: "PARTIALLY_RESOLVED",
    confirmationState: "PARTIALLY_RESOLVED",
    openedHoursAgo: 340,
    lastActionHoursAgo: 80,
    tags: ["partly-resolved", "appealed", "streetlight-cluster"],
  },
  {
    title: "Pension correction partly completed",
    citizen: 1,
    organizationCode: "DEMO-PENSION",
    categoryCode: "DEMO-PENSION-DELAY",
    location: pensionLocations[1][0],
    state: pensionLocations[1][1],
    district: pensionLocations[1][2],
    submittedHoursAgo: 420,
    slaWindowHours: 504,
    administrativeState: "RESOLUTION_PROVIDED",
    outcomeState: "PARTIALLY_RESOLVED",
    confirmationState: "PARTIALLY_RESOLVED",
    openedHoursAgo: 400,
    lastActionHoursAgo: 100,
    tags: ["partly-resolved", "pension-cluster"],
  },
  {
    title: "Water pressure not restored after response",
    citizen: 2,
    organizationCode: "DEMO-WATER",
    categoryCode: "DEMO-WATER-SUPPLY",
    location: waterLocations[0][0],
    state: waterLocations[0][1],
    district: waterLocations[0][2],
    submittedHoursAgo: 360,
    slaWindowHours: 336,
    administrativeState: "APPEAL_UNDER_REVIEW",
    outcomeState: "UNRESOLVED",
    confirmationState: "NOT_RESOLVED",
    openedHoursAgo: 340,
    lastActionHoursAgo: 90,
    tags: ["not-resolved", "appealed", "water-cluster"],
  },
  {
    title: "Streetlight remained dark after closure visit",
    citizen: 3,
    organizationCode: "DEMO-URBAN",
    categoryCode: "DEMO-STREETLIGHT",
    location: urbanLocations[2][0],
    state: urbanLocations[2][1],
    district: urbanLocations[2][2],
    submittedHoursAgo: 500,
    slaWindowHours: 360,
    administrativeState: "APPEAL_UNDER_REVIEW",
    outcomeState: "UNRESOLVED",
    confirmationState: "NOT_RESOLVED",
    openedHoursAgo: 480,
    lastActionHoursAgo: 180,
    tags: ["not-resolved", "appealed", "streetlight-cluster"],
  },
  {
    title: "Pension appeal filed for missing month",
    citizen: 4,
    organizationCode: "DEMO-PENSION",
    categoryCode: "DEMO-PENSION-DELAY",
    location: pensionLocations[0][0],
    state: pensionLocations[0][1],
    district: pensionLocations[0][2],
    submittedHoursAgo: 520,
    slaWindowHours: 504,
    administrativeState: "APPEAL_FILED",
    outcomeState: "PARTIALLY_RESOLVED",
    confirmationState: "PARTIALLY_RESOLVED",
    openedHoursAgo: 500,
    lastActionHoursAgo: 200,
    tags: ["appealed", "pension-cluster"],
  },
  {
    title: "Decided appeal on repeated streetlight outage",
    citizen: 0,
    organizationCode: "DEMO-URBAN",
    categoryCode: "DEMO-STREETLIGHT",
    location: urbanLocations[0][0],
    state: urbanLocations[0][1],
    district: urbanLocations[0][2],
    submittedHoursAgo: 800,
    slaWindowHours: 360,
    administrativeState: "APPEAL_DECIDED",
    outcomeState: "PARTIALLY_RESOLVED",
    confirmationState: "PARTIALLY_RESOLVED",
    openedHoursAgo: 780,
    lastActionHoursAgo: 400,
    tags: ["appealed", "appeal-decided", "streetlight-cluster"],
  },
  {
    title: "Decided pension appeal with corrective direction",
    citizen: 1,
    organizationCode: "DEMO-PENSION",
    categoryCode: "DEMO-PENSION-DELAY",
    location: pensionLocations[1][0],
    state: pensionLocations[1][1],
    district: pensionLocations[1][2],
    submittedHoursAgo: 900,
    slaWindowHours: 504,
    administrativeState: "APPEAL_DECIDED",
    outcomeState: "PARTIALLY_RESOLVED",
    confirmationState: "NOT_RESOLVED",
    openedHoursAgo: 880,
    lastActionHoursAgo: 500,
    tags: ["appealed", "appeal-decided", "pension-cluster"],
  },
  {
    title: "Streetlight case transferred to urban office",
    citizen: 2,
    organizationCode: "DEMO-URBAN",
    categoryCode: "DEMO-STREETLIGHT",
    location: urbanLocations[1][0],
    state: urbanLocations[1][1],
    district: urbanLocations[1][2],
    submittedHoursAgo: 120,
    slaWindowHours: 360,
    administrativeState: "ASSIGNED",
    outcomeState: "UNRESOLVED",
    confirmationState: "NOT_REQUESTED",
    openedHoursAgo: 100,
    lastActionHoursAgo: 24,
    tags: ["transferred", "streetlight-cluster"],
  },
  {
    title: "Water case flagged for transfer within 48 hours",
    citizen: 3,
    organizationCode: "DEMO-WATER",
    categoryCode: "DEMO-WATER-SUPPLY",
    location: waterLocations[1][0],
    state: waterLocations[1][1],
    district: waterLocations[1][2],
    submittedHoursAgo: 80,
    slaWindowHours: 336,
    administrativeState: "UNDER_EXAMINATION",
    outcomeState: "UNRESOLVED",
    confirmationState: "NOT_REQUESTED",
    openedHoursAgo: 70,
    lastActionHoursAgo: 20,
    tags: ["transfer-risk", "water-cluster"],
  },
  {
    title: "Citizen reminder on delayed streetlight inspection",
    citizen: 4,
    organizationCode: "DEMO-URBAN",
    categoryCode: "DEMO-STREETLIGHT",
    location: urbanLocations[0][0],
    state: urbanLocations[0][1],
    district: urbanLocations[0][2],
    submittedHoursAgo: 160,
    slaWindowHours: 360,
    administrativeState: "UNDER_EXAMINATION",
    outcomeState: "UNRESOLVED",
    confirmationState: "NOT_REQUESTED",
    openedHoursAgo: 150,
    lastActionHoursAgo: 48,
    reminderCount: 1,
    tags: ["reminder", "streetlight-cluster"],
  },
  {
    title: "Reminder contribution capped on pension case",
    citizen: 0,
    organizationCode: "DEMO-PENSION",
    categoryCode: "DEMO-PENSION-DELAY",
    location: pensionLocations[0][0],
    state: pensionLocations[0][1],
    district: pensionLocations[0][2],
    submittedHoursAgo: 180,
    slaWindowHours: 504,
    administrativeState: "UNDER_EXAMINATION",
    outcomeState: "UNRESOLVED",
    confirmationState: "NOT_REQUESTED",
    openedHoursAgo: 170,
    lastActionHoursAgo: 24,
    reminderCount: 8,
    tags: ["reminder", "reminder-cap", "pension-cluster"],
  },
];

export const DEMO_CASES: readonly DemoCaseDefinition[] = rawCases.map((entry, index) => ({
  ...entry,
  title: `${REVIEWER_CASE_TITLE_PREFIX} ${entry.title}`,
  citizen: index % 2,
  id: demoId(1_001 + index),
  reference: `CPG-2026-D3A${(index + 1).toString(16).toUpperCase().padStart(17, "0")}`,
}));

export const DEMO_CLUSTERS = [
  {
    id: demoId(13_001),
    title: "[DEMO] Repeated streetlight outages in Ward 12/14",
    summary:
      "Stored prototype cluster for repeated streetlight faults; not an AI or official finding.",
    organizationCode: "DEMO-URBAN",
    categoryCode: "DEMO-STREETLIGHT",
    tag: "streetlight-cluster" as const,
  },
  {
    id: demoId(13_002),
    title: "[DEMO] Water-supply interruptions in Nashik wards",
    summary:
      "Stored prototype cluster for repeated water-supply reports; not an AI or official finding.",
    organizationCode: "DEMO-WATER",
    categoryCode: "DEMO-WATER-SUPPLY",
    tag: "water-cluster" as const,
  },
  {
    id: demoId(13_003),
    title: "[DEMO] Pension payment delays",
    summary:
      "Stored prototype cluster for repeated pension-delay reports; not an AI or official finding.",
    organizationCode: "DEMO-PENSION",
    categoryCode: "DEMO-PENSION-DELAY",
    tag: "pension-cluster" as const,
  },
] as const;

export const REQUIRED_DEMO_TAGS: readonly DemoCaseTag[] = [
  "fresh",
  "unopened",
  "sla-risk",
  "critical",
  "waiting-citizen",
  "clarification-open",
  "clarification-complete",
  "documents-partial",
  "documents-complete",
  "interim",
  "resolution-review",
  "confirmed-resolved",
  "partly-resolved",
  "not-resolved",
  "appealed",
  "appeal-decided",
  "transferred",
  "transfer-risk",
  "reminder",
  "reminder-cap",
  "manual-routing",
  "closure-ready",
  "streetlight-cluster",
  "water-cluster",
  "pension-cluster",
];

export function demoScenarioCounts() {
  return Object.fromEntries(
    REQUIRED_DEMO_TAGS.map((tag) => [
      tag,
      DEMO_CASES.filter((item) => item.tags.includes(tag)).length,
    ]),
  ) as Record<DemoCaseTag, number>;
}
