/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppealStatusRouteImport } from './routes/appeal-status'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CitizenRouteImport } from './routes/citizen'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as OfficeRouteImport } from './routes/office'
import { Route as TrackRouteImport } from './routes/track'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthOfficerLoginRouteImport } from './routes/auth.officer-login'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as CitizenIndexRouteImport } from './routes/citizen.index'
import { Route as CitizenNotificationsRouteImport } from './routes/citizen.notifications'
import { Route as CitizenProfileRouteImport } from './routes/citizen.profile'
import { Route as DashboardAppealsRouteImport } from './routes/dashboard.appeals'
import { Route as DashboardPublicRouteImport } from './routes/dashboard.public'
import { Route as OfficeIndexRouteImport } from './routes/office.index'
import { Route as OfficeAnalyticsRouteImport } from './routes/office.analytics'
import { Route as OfficeSystemicIssuesRouteImport } from './routes/office.systemic-issues'
import { Route as OfficersAppealsRouteImport } from './routes/officers.appeals'
import { Route as OfficersCentralRouteImport } from './routes/officers.central'
import { Route as OfficersStatesRouteImport } from './routes/officers.states'
import { Route as CitizenAppealsIdRouteImport } from './routes/citizen.appeals.$id'
import { Route as CitizenGrievancesIdRouteImport } from './routes/citizen.grievances.$id'
import { Route as CitizenGrievancesNewRouteImport } from './routes/citizen.grievances.new'
import { Route as OfficeAppealsIndexRouteImport } from './routes/office.appeals.index'
import { Route as OfficeAppealsIdRouteImport } from './routes/office.appeals.$id'
import { Route as OfficeCasesIndexRouteImport } from './routes/office.cases.index'
import { Route as OfficeCasesIdRouteImport } from './routes/office.cases.$id'
import { Route as CitizenGrievancesIdAppealRouteImport } from './routes/citizen.grievances.$id.appeal'
import { Route as CitizenGrievancesIdResolutionRouteImport } from './routes/citizen.grievances.$id.resolution'
import { Route as CitizenGrievancesIdSubmittedRouteImport } from './routes/citizen.grievances.$id.submitted'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppealStatusRoute = AppealStatusRouteImport.update({
  id: '/appeal-status',
  path: '/appeal-status',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenRoute = CitizenRouteImport.update({
  id: '/citizen',
  path: '/citizen',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeRoute = OfficeRouteImport.update({
  id: '/office',
  path: '/office',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOfficerLoginRoute = AuthOfficerLoginRouteImport.update({
  id: '/officer-login',
  path: '/officer-login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const CitizenIndexRoute = CitizenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenNotificationsRoute = CitizenNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenProfileRoute = CitizenProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CitizenRoute,
} as any)
const DashboardAppealsRoute = DashboardAppealsRouteImport.update({
  id: '/dashboard/appeals',
  path: '/dashboard/appeals',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPublicRoute = DashboardPublicRouteImport.update({
  id: '/dashboard/public',
  path: '/dashboard/public',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeIndexRoute = OfficeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OfficeRoute,
} as any)
const OfficeAnalyticsRoute = OfficeAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => OfficeRoute,
} as any)
const OfficeSystemicIssuesRoute = OfficeSystemicIssuesRouteImport.update({
  id: '/systemic-issues',
  path: '/systemic-issues',
  getParentRoute: () => OfficeRoute,
} as any)
const OfficersAppealsRoute = OfficersAppealsRouteImport.update({
  id: '/officers/appeals',
  path: '/officers/appeals',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficersCentralRoute = OfficersCentralRouteImport.update({
  id: '/officers/central',
  path: '/officers/central',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficersStatesRoute = OfficersStatesRouteImport.update({
  id: '/officers/states',
  path: '/officers/states',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenAppealsIdRoute = CitizenAppealsIdRouteImport.update({
  id: '/appeals/$id',
  path: '/appeals/$id',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenGrievancesIdRoute = CitizenGrievancesIdRouteImport.update({
  id: '/grievances/$id',
  path: '/grievances/$id',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenGrievancesNewRoute = CitizenGrievancesNewRouteImport.update({
  id: '/grievances/new',
  path: '/grievances/new',
  getParentRoute: () => CitizenRoute,
} as any)
const OfficeAppealsIndexRoute = OfficeAppealsIndexRouteImport.update({
  id: '/appeals/',
  path: '/appeals/',
  getParentRoute: () => OfficeRoute,
} as any)
const OfficeAppealsIdRoute = OfficeAppealsIdRouteImport.update({
  id: '/appeals/$id',
  path: '/appeals/$id',
  getParentRoute: () => OfficeRoute,
} as any)
const OfficeCasesIndexRoute = OfficeCasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => OfficeRoute,
} as any)
const OfficeCasesIdRoute = OfficeCasesIdRouteImport.update({
  id: '/cases/$id',
  path: '/cases/$id',
  getParentRoute: () => OfficeRoute,
} as any)
const CitizenGrievancesIdAppealRoute =
  CitizenGrievancesIdAppealRouteImport.update({
    id: '/appeal',
    path: '/appeal',
    getParentRoute: () => CitizenGrievancesIdRoute,
  } as any)
const CitizenGrievancesIdResolutionRoute =
  CitizenGrievancesIdResolutionRouteImport.update({
    id: '/resolution',
    path: '/resolution',
    getParentRoute: () => CitizenGrievancesIdRoute,
  } as any)
const CitizenGrievancesIdSubmittedRoute =
  CitizenGrievancesIdSubmittedRouteImport.update({
    id: '/submitted',
    path: '/submitted',
    getParentRoute: () => CitizenGrievancesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appeal-status': typeof AppealStatusRoute
  '/auth': typeof AuthRouteWithChildren
  '/citizen': typeof CitizenRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/office': typeof OfficeRouteWithChildren
  '/track': typeof TrackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/officer-login': typeof AuthOfficerLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/citizen/notifications': typeof CitizenNotificationsRoute
  '/citizen/profile': typeof CitizenProfileRoute
  '/dashboard/appeals': typeof DashboardAppealsRoute
  '/dashboard/public': typeof DashboardPublicRoute
  '/office/analytics': typeof OfficeAnalyticsRoute
  '/office/systemic-issues': typeof OfficeSystemicIssuesRoute
  '/officers/appeals': typeof OfficersAppealsRoute
  '/officers/central': typeof OfficersCentralRoute
  '/officers/states': typeof OfficersStatesRoute
  '/admin/': typeof AdminIndexRoute
  '/citizen/': typeof CitizenIndexRoute
  '/office/': typeof OfficeIndexRoute
  '/citizen/appeals/$id': typeof CitizenAppealsIdRoute
  '/citizen/grievances/$id': typeof CitizenGrievancesIdRouteWithChildren
  '/citizen/grievances/new': typeof CitizenGrievancesNewRoute
  '/office/appeals/$id': typeof OfficeAppealsIdRoute
  '/office/cases/$id': typeof OfficeCasesIdRoute
  '/office/appeals/': typeof OfficeAppealsIndexRoute
  '/office/cases/': typeof OfficeCasesIndexRoute
  '/citizen/grievances/$id/appeal': typeof CitizenGrievancesIdAppealRoute
  '/citizen/grievances/$id/resolution': typeof CitizenGrievancesIdResolutionRoute
  '/citizen/grievances/$id/submitted': typeof CitizenGrievancesIdSubmittedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appeal-status': typeof AppealStatusRoute
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/track': typeof TrackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/officer-login': typeof AuthOfficerLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/citizen/notifications': typeof CitizenNotificationsRoute
  '/citizen/profile': typeof CitizenProfileRoute
  '/dashboard/appeals': typeof DashboardAppealsRoute
  '/dashboard/public': typeof DashboardPublicRoute
  '/office/analytics': typeof OfficeAnalyticsRoute
  '/office/systemic-issues': typeof OfficeSystemicIssuesRoute
  '/officers/appeals': typeof OfficersAppealsRoute
  '/officers/central': typeof OfficersCentralRoute
  '/officers/states': typeof OfficersStatesRoute
  '/admin': typeof AdminIndexRoute
  '/citizen': typeof CitizenIndexRoute
  '/office': typeof OfficeIndexRoute
  '/citizen/appeals/$id': typeof CitizenAppealsIdRoute
  '/citizen/grievances/$id': typeof CitizenGrievancesIdRouteWithChildren
  '/citizen/grievances/new': typeof CitizenGrievancesNewRoute
  '/office/appeals/$id': typeof OfficeAppealsIdRoute
  '/office/cases/$id': typeof OfficeCasesIdRoute
  '/office/appeals': typeof OfficeAppealsIndexRoute
  '/office/cases': typeof OfficeCasesIndexRoute
  '/citizen/grievances/$id/appeal': typeof CitizenGrievancesIdAppealRoute
  '/citizen/grievances/$id/resolution': typeof CitizenGrievancesIdResolutionRoute
  '/citizen/grievances/$id/submitted': typeof CitizenGrievancesIdSubmittedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appeal-status': typeof AppealStatusRoute
  '/auth': typeof AuthRouteWithChildren
  '/citizen': typeof CitizenRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/office': typeof OfficeRouteWithChildren
  '/track': typeof TrackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/officer-login': typeof AuthOfficerLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/citizen/notifications': typeof CitizenNotificationsRoute
  '/citizen/profile': typeof CitizenProfileRoute
  '/dashboard/appeals': typeof DashboardAppealsRoute
  '/dashboard/public': typeof DashboardPublicRoute
  '/office/analytics': typeof OfficeAnalyticsRoute
  '/office/systemic-issues': typeof OfficeSystemicIssuesRoute
  '/officers/appeals': typeof OfficersAppealsRoute
  '/officers/central': typeof OfficersCentralRoute
  '/officers/states': typeof OfficersStatesRoute
  '/admin/': typeof AdminIndexRoute
  '/citizen/': typeof CitizenIndexRoute
  '/office/': typeof OfficeIndexRoute
  '/citizen/appeals/$id': typeof CitizenAppealsIdRoute
  '/citizen/grievances/$id': typeof CitizenGrievancesIdRouteWithChildren
  '/citizen/grievances/new': typeof CitizenGrievancesNewRoute
  '/office/appeals/$id': typeof OfficeAppealsIdRoute
  '/office/cases/$id': typeof OfficeCasesIdRoute
  '/office/appeals/': typeof OfficeAppealsIndexRoute
  '/office/cases/': typeof OfficeCasesIndexRoute
  '/citizen/grievances/$id/appeal': typeof CitizenGrievancesIdAppealRoute
  '/citizen/grievances/$id/resolution': typeof CitizenGrievancesIdResolutionRoute
  '/citizen/grievances/$id/submitted': typeof CitizenGrievancesIdSubmittedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/appeal-status'
    | '/auth'
    | '/citizen'
    | '/contact'
    | '/faq'
    | '/office'
    | '/track'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/officer-login'
    | '/auth/signup'
    | '/citizen/notifications'
    | '/citizen/profile'
    | '/dashboard/appeals'
    | '/dashboard/public'
    | '/office/analytics'
    | '/office/systemic-issues'
    | '/officers/appeals'
    | '/officers/central'
    | '/officers/states'
    | '/admin/'
    | '/citizen/'
    | '/office/'
    | '/citizen/appeals/$id'
    | '/citizen/grievances/$id'
    | '/citizen/grievances/new'
    | '/office/appeals/$id'
    | '/office/cases/$id'
    | '/office/appeals/'
    | '/office/cases/'
    | '/citizen/grievances/$id/appeal'
    | '/citizen/grievances/$id/resolution'
    | '/citizen/grievances/$id/submitted'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/appeal-status'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/track'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/officer-login'
    | '/auth/signup'
    | '/citizen/notifications'
    | '/citizen/profile'
    | '/dashboard/appeals'
    | '/dashboard/public'
    | '/office/analytics'
    | '/office/systemic-issues'
    | '/officers/appeals'
    | '/officers/central'
    | '/officers/states'
    | '/admin'
    | '/citizen'
    | '/office'
    | '/citizen/appeals/$id'
    | '/citizen/grievances/$id'
    | '/citizen/grievances/new'
    | '/office/appeals/$id'
    | '/office/cases/$id'
    | '/office/appeals'
    | '/office/cases'
    | '/citizen/grievances/$id/appeal'
    | '/citizen/grievances/$id/resolution'
    | '/citizen/grievances/$id/submitted'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/appeal-status'
    | '/auth'
    | '/citizen'
    | '/contact'
    | '/faq'
    | '/office'
    | '/track'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/officer-login'
    | '/auth/signup'
    | '/citizen/notifications'
    | '/citizen/profile'
    | '/dashboard/appeals'
    | '/dashboard/public'
    | '/office/analytics'
    | '/office/systemic-issues'
    | '/officers/appeals'
    | '/officers/central'
    | '/officers/states'
    | '/admin/'
    | '/citizen/'
    | '/office/'
    | '/citizen/appeals/$id'
    | '/citizen/grievances/$id'
    | '/citizen/grievances/new'
    | '/office/appeals/$id'
    | '/office/cases/$id'
    | '/office/appeals/'
    | '/office/cases/'
    | '/citizen/grievances/$id/appeal'
    | '/citizen/grievances/$id/resolution'
    | '/citizen/grievances/$id/submitted'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppealStatusRoute: typeof AppealStatusRoute
  AuthRoute: typeof AuthRouteWithChildren
  CitizenRoute: typeof CitizenRouteWithChildren
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  OfficeRoute: typeof OfficeRouteWithChildren
  TrackRoute: typeof TrackRoute
  DashboardAppealsRoute: typeof DashboardAppealsRoute
  DashboardPublicRoute: typeof DashboardPublicRoute
  OfficersAppealsRoute: typeof OfficersAppealsRoute
  OfficersCentralRoute: typeof OfficersCentralRoute
  OfficersStatesRoute: typeof OfficersStatesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appeal-status': {
      id: '/appeal-status'
      path: '/appeal-status'
      fullPath: '/appeal-status'
      preLoaderRoute: typeof AppealStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen': {
      id: '/citizen'
      path: '/citizen'
      fullPath: '/citizen'
      preLoaderRoute: typeof CitizenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office': {
      id: '/office'
      path: '/office'
      fullPath: '/office'
      preLoaderRoute: typeof OfficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/officer-login': {
      id: '/auth/officer-login'
      path: '/officer-login'
      fullPath: '/auth/officer-login'
      preLoaderRoute: typeof AuthOfficerLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/citizen/': {
      id: '/citizen/'
      path: '/'
      fullPath: '/citizen/'
      preLoaderRoute: typeof CitizenIndexRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/notifications': {
      id: '/citizen/notifications'
      path: '/notifications'
      fullPath: '/citizen/notifications'
      preLoaderRoute: typeof CitizenNotificationsRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/profile': {
      id: '/citizen/profile'
      path: '/profile'
      fullPath: '/citizen/profile'
      preLoaderRoute: typeof CitizenProfileRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/dashboard/appeals': {
      id: '/dashboard/appeals'
      path: '/dashboard/appeals'
      fullPath: '/dashboard/appeals'
      preLoaderRoute: typeof DashboardAppealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/public': {
      id: '/dashboard/public'
      path: '/dashboard/public'
      fullPath: '/dashboard/public'
      preLoaderRoute: typeof DashboardPublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office/': {
      id: '/office/'
      path: '/'
      fullPath: '/office/'
      preLoaderRoute: typeof OfficeIndexRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/office/analytics': {
      id: '/office/analytics'
      path: '/analytics'
      fullPath: '/office/analytics'
      preLoaderRoute: typeof OfficeAnalyticsRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/office/systemic-issues': {
      id: '/office/systemic-issues'
      path: '/systemic-issues'
      fullPath: '/office/systemic-issues'
      preLoaderRoute: typeof OfficeSystemicIssuesRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/officers/appeals': {
      id: '/officers/appeals'
      path: '/officers/appeals'
      fullPath: '/officers/appeals'
      preLoaderRoute: typeof OfficersAppealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officers/central': {
      id: '/officers/central'
      path: '/officers/central'
      fullPath: '/officers/central'
      preLoaderRoute: typeof OfficersCentralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officers/states': {
      id: '/officers/states'
      path: '/officers/states'
      fullPath: '/officers/states'
      preLoaderRoute: typeof OfficersStatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/appeals/$id': {
      id: '/citizen/appeals/$id'
      path: '/appeals/$id'
      fullPath: '/citizen/appeals/$id'
      preLoaderRoute: typeof CitizenAppealsIdRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/grievances/$id': {
      id: '/citizen/grievances/$id'
      path: '/grievances/$id'
      fullPath: '/citizen/grievances/$id'
      preLoaderRoute: typeof CitizenGrievancesIdRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/grievances/new': {
      id: '/citizen/grievances/new'
      path: '/grievances/new'
      fullPath: '/citizen/grievances/new'
      preLoaderRoute: typeof CitizenGrievancesNewRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/office/appeals/': {
      id: '/office/appeals/'
      path: '/appeals'
      fullPath: '/office/appeals/'
      preLoaderRoute: typeof OfficeAppealsIndexRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/office/appeals/$id': {
      id: '/office/appeals/$id'
      path: '/appeals/$id'
      fullPath: '/office/appeals/$id'
      preLoaderRoute: typeof OfficeAppealsIdRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/office/cases/': {
      id: '/office/cases/'
      path: '/cases'
      fullPath: '/office/cases/'
      preLoaderRoute: typeof OfficeCasesIndexRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/office/cases/$id': {
      id: '/office/cases/$id'
      path: '/cases/$id'
      fullPath: '/office/cases/$id'
      preLoaderRoute: typeof OfficeCasesIdRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/citizen/grievances/$id/appeal': {
      id: '/citizen/grievances/$id/appeal'
      path: '/appeal'
      fullPath: '/citizen/grievances/$id/appeal'
      preLoaderRoute: typeof CitizenGrievancesIdAppealRouteImport
      parentRoute: typeof CitizenGrievancesIdRoute
    }
    '/citizen/grievances/$id/resolution': {
      id: '/citizen/grievances/$id/resolution'
      path: '/resolution'
      fullPath: '/citizen/grievances/$id/resolution'
      preLoaderRoute: typeof CitizenGrievancesIdResolutionRouteImport
      parentRoute: typeof CitizenGrievancesIdRoute
    }
    '/citizen/grievances/$id/submitted': {
      id: '/citizen/grievances/$id/submitted'
      path: '/submitted'
      fullPath: '/citizen/grievances/$id/submitted'
      preLoaderRoute: typeof CitizenGrievancesIdSubmittedRouteImport
      parentRoute: typeof CitizenGrievancesIdRoute
    }
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthOfficerLoginRoute: typeof AuthOfficerLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthOfficerLoginRoute: AuthOfficerLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface CitizenGrievancesIdRouteChildren {
  CitizenGrievancesIdAppealRoute: typeof CitizenGrievancesIdAppealRoute
  CitizenGrievancesIdResolutionRoute: typeof CitizenGrievancesIdResolutionRoute
  CitizenGrievancesIdSubmittedRoute: typeof CitizenGrievancesIdSubmittedRoute
}

const CitizenGrievancesIdRouteChildren: CitizenGrievancesIdRouteChildren = {
  CitizenGrievancesIdAppealRoute: CitizenGrievancesIdAppealRoute,
  CitizenGrievancesIdResolutionRoute: CitizenGrievancesIdResolutionRoute,
  CitizenGrievancesIdSubmittedRoute: CitizenGrievancesIdSubmittedRoute,
}

const CitizenGrievancesIdRouteWithChildren =
  CitizenGrievancesIdRoute._addFileChildren(CitizenGrievancesIdRouteChildren)

interface CitizenRouteChildren {
  CitizenNotificationsRoute: typeof CitizenNotificationsRoute
  CitizenProfileRoute: typeof CitizenProfileRoute
  CitizenIndexRoute: typeof CitizenIndexRoute
  CitizenAppealsIdRoute: typeof CitizenAppealsIdRoute
  CitizenGrievancesIdRoute: typeof CitizenGrievancesIdRouteWithChildren
  CitizenGrievancesNewRoute: typeof CitizenGrievancesNewRoute
}

const CitizenRouteChildren: CitizenRouteChildren = {
  CitizenNotificationsRoute: CitizenNotificationsRoute,
  CitizenProfileRoute: CitizenProfileRoute,
  CitizenIndexRoute: CitizenIndexRoute,
  CitizenAppealsIdRoute: CitizenAppealsIdRoute,
  CitizenGrievancesIdRoute: CitizenGrievancesIdRouteWithChildren,
  CitizenGrievancesNewRoute: CitizenGrievancesNewRoute,
}

const CitizenRouteWithChildren =
  CitizenRoute._addFileChildren(CitizenRouteChildren)

interface OfficeRouteChildren {
  OfficeAnalyticsRoute: typeof OfficeAnalyticsRoute
  OfficeSystemicIssuesRoute: typeof OfficeSystemicIssuesRoute
  OfficeIndexRoute: typeof OfficeIndexRoute
  OfficeAppealsIdRoute: typeof OfficeAppealsIdRoute
  OfficeCasesIdRoute: typeof OfficeCasesIdRoute
  OfficeAppealsIndexRoute: typeof OfficeAppealsIndexRoute
  OfficeCasesIndexRoute: typeof OfficeCasesIndexRoute
}

const OfficeRouteChildren: OfficeRouteChildren = {
  OfficeAnalyticsRoute: OfficeAnalyticsRoute,
  OfficeSystemicIssuesRoute: OfficeSystemicIssuesRoute,
  OfficeIndexRoute: OfficeIndexRoute,
  OfficeAppealsIdRoute: OfficeAppealsIdRoute,
  OfficeCasesIdRoute: OfficeCasesIdRoute,
  OfficeAppealsIndexRoute: OfficeAppealsIndexRoute,
  OfficeCasesIndexRoute: OfficeCasesIndexRoute,
}

const OfficeRouteWithChildren =
  OfficeRoute._addFileChildren(OfficeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppealStatusRoute: AppealStatusRoute,
  AuthRoute: AuthRouteWithChildren,
  CitizenRoute: CitizenRouteWithChildren,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  OfficeRoute: OfficeRouteWithChildren,
  TrackRoute: TrackRoute,
  DashboardAppealsRoute: DashboardAppealsRoute,
  DashboardPublicRoute: DashboardPublicRoute,
  OfficersAppealsRoute: OfficersAppealsRoute,
  OfficersCentralRoute: OfficersCentralRoute,
  OfficersStatesRoute: OfficersStatesRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
